# Generated by Django 5.0.7 on 2024-12-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfield',
            name='work_achievements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentfield',
            name='work_company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='documentfield',
            name='work_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentfield',
            name='work_from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentfield',
            name='work_job_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='documentfield',
            name='work_to_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentfield',
            name='education',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='documentfield',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentfield',
            name='work_experience',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
