# Generated by Django 5.1.4 on 2024-12-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_documentfield_work_achievements_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentfield',
            name='work_achievements',
        ),
        migrations.RemoveField(
            model_name='documentfield',
            name='work_company_name',
        ),
        migrations.RemoveField(
            model_name='documentfield',
            name='work_description',
        ),
        migrations.RemoveField(
            model_name='documentfield',
            name='work_experience',
        ),
        migrations.RemoveField(
            model_name='documentfield',
            name='work_from_date',
        ),
        migrations.RemoveField(
            model_name='documentfield',
            name='work_job_title',
        ),
        migrations.RemoveField(
            model_name='documentfield',
            name='work_to_date',
        ),
        migrations.AddField(
            model_name='documentfield',
            name='experience',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
