# Generated by Django 5.1 on 2024-11-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_footersection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footersection',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
