# Generated by Django 5.0.7 on 2024-12-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_documentfield_work_achievements_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_of_experience', models.PositiveIntegerField(default=0, help_text='Enter the number of years of experience')),
                ('is_student', models.BooleanField(default=False, help_text='Indicate whether the user is a student.')),
            ],
        ),
    ]
