# Generated by Django 5.0.7 on 2024-11-29 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_footersection_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Document Category',
                'verbose_name_plural': 'Document Categories',
            },
        ),
        migrations.CreateModel(
            name='DocumentField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(null=True, upload_to='resume_images/')),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('certification', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('linkedin', models.CharField(max_length=100, null=True)),
                ('github', models.CharField(max_length=100, null=True)),
                ('website', models.CharField(max_length=100, null=True)),
                ('phone', models.IntegerField(max_length=20, null=True)),
                ('project', models.TextField(max_length=100, null=True)),
                ('address', models.TextField(null=True)),
                ('skill', models.TextField(null=True)),
                ('education', models.TextField(null=True)),
                ('work_experience', models.TextField(null=True)),
                ('achievement', models.TextField(null=True)),
                ('hobbies', models.TextField(null=True)),
                ('language', models.TextField(null=True)),
                ('reference', models.TextField(null=True)),
                ('extra', models.TextField(null=True)),
                ('watermark', models.ImageField(null=True, upload_to='resume_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='resume_templates/')),
                ('name', models.CharField(max_length=100)),
                ('template', models.FileField(upload_to='resume_templates/')),
                ('html', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.documentcategory')),
            ],
        ),
        migrations.RemoveField(
            model_name='resume',
            name='template',
        ),
        migrations.RemoveField(
            model_name='resumefile',
            name='resume',
        ),
        migrations.DeleteModel(
            name='ResumeCategory',
        ),
        migrations.AddField(
            model_name='documentfield',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.template'),
        ),
        migrations.DeleteModel(
            name='ResumeTemplate',
        ),
        migrations.DeleteModel(
            name='Resume',
        ),
        migrations.DeleteModel(
            name='ResumeFile',
        ),
    ]
