# Generated by Django 5.0.7 on 2024-12-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='decription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
