# Generated by Django 5.1.4 on 2025-01-01 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the promotion', max_length=200)),
                ('subtitle', models.CharField(help_text='Subtitle or tagline for the promotion', max_length=300)),
                ('discount_percentage', models.PositiveIntegerField(help_text='Discount percentage, e.g., 50 for 50%')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the promotion', null=True)),
                ('cta_text', models.CharField(default='Shop Now', help_text='Text for the call-to-action button', max_length=50)),
                ('image', models.ImageField(help_text='Image for the promotion', upload_to='promotions/')),
                ('is_active', models.BooleanField(default=True, help_text='Is this promotion currently active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Brand name', max_length=100)),
                ('logo', models.ImageField(help_text='Logo of the brand', upload_to='brands/')),
            ],
        ),
    ]
