# Generated by Django 5.0.7 on 2024-11-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_documentcategory_documentfield_template_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentcategory',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
