# Generated by Django 5.1 on 2024-11-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_appointment_appointment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumecategory',
            name='image',
            field=models.ImageField(null=True, upload_to='resume_categories/'),
        ),
    ]
