# Generated by Django 5.0.7 on 2025-01-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='document',
        ),
        migrations.AddField(
            model_name='profile',
            name='documents',
            field=models.ManyToManyField(blank=True, to='api.documentfield'),
        ),
    ]
