# Generated by Django 5.1 on 2024-11-22 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_pricing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricing',
            name='user',
        ),
    ]
