# Generated by Django 5.0.7 on 2025-01-02 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_profile_document_profile_documents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='documents',
            new_name='document',
        ),
    ]
