# Generated by Django 5.1.3 on 2024-11-29 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_documentcategory_icon'),
        ('api', '0007_alter_resume_achievements_alter_resume_address_and_more'),
    ]

    operations = [
    ]
