# Generated by Django 5.1.4 on 2025-01-01 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_branding_cta_text_remove_branding_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the resume template', max_length=255)),
                ('description', models.TextField(help_text='Description of the resume template')),
                ('image_url_1', models.URLField(help_text='URL of the first image representing the resume template')),
                ('image_url_2', models.URLField(blank=True, help_text='URL of the second image representing the resume template', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the template was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the template was last updated')),
            ],
        ),
    ]
