# Generated by Django 5.1.3 on 2024-11-29 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_merge_20241130_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfield',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.template'),
        ),
    ]
