# Generated by Django 5.1.4 on 2025-01-01 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_resumelayout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumelayout',
            name='image_url_1',
        ),
        migrations.RemoveField(
            model_name='resumelayout',
            name='image_url_2',
        ),
        migrations.AddField(
            model_name='resumelayout',
            name='image_1',
            field=models.ImageField(default=1, help_text='Upload the first image for the resume template', upload_to='resume_templates/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resumelayout',
            name='image_2',
            field=models.ImageField(blank=True, help_text='Upload the second image for the resume template (optional)', null=True, upload_to='resume_templates/'),
        ),
    ]
