# Generated by Django 5.1 on 2024-11-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='image',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='name',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
