# Generated by Django 5.1.3 on 2024-12-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_documentfield_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='template',
            field=models.TextField(),
        ),
    ]
