# Generated by Django 5.1.3 on 2024-12-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_template_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfield',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='resume_images/'),
        ),
    ]
