# Generated by Django 5.1.4 on 2025-01-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_galleryimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galleryimage',
            old_name='image',
            new_name='image_1',
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='image_2',
            field=models.ImageField(default=1, upload_to='gallery_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='image_3',
            field=models.ImageField(default=1, upload_to='gallery_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='gallery_images/'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='gallery_images/'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='image_6',
            field=models.ImageField(blank=True, null=True, upload_to='gallery_images/'),
        ),
    ]
