# Generated by Django 5.1.3 on 2024-11-23 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_faq'),
        ('api', '0011_herosection'),
    ]

    operations = [
    ]
