# Generated by Django 5.1.4 on 2025-01-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_image_galleryimage_image_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the content section', max_length=255)),
                ('description', models.TextField(help_text='Description of the content section')),
                ('label', models.CharField(help_text='Label for the statistic (e.g., Users, Subscribes)', max_length=255)),
                ('value', models.CharField(help_text='Value of the statistic (e.g., 2.7K, 1.8K)', max_length=50)),
                ('icon', models.CharField(help_text='Icon for the statistic (e.g., fa-users for FontAwesome icons)', max_length=255)),
            ],
        ),
    ]
