# Generated by Django 5.1.4 on 2025-01-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='image',
            field=models.ImageField(default=1, upload_to='counters/'),
            preserve_default=False,
        ),
    ]
