# Generated by Django 5.1.4 on 2025-01-02 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_counter_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counter',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='counter',
            name='label',
        ),
        migrations.RemoveField(
            model_name='counter',
            name='value',
        ),
        migrations.AlterField(
            model_name='counter',
            name='image',
            field=models.ImageField(help_text='Image for the content section', upload_to='counters/'),
        ),
        migrations.CreateModel(
            name='CounterDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Label for the statistic (e.g., Users, Subscribes)', max_length=255)),
                ('value', models.CharField(help_text='Value of the statistic (e.g., 2.7K, 1.8K)', max_length=50)),
                ('icon', models.CharField(help_text='Icon for the statistic (e.g., fa-users for FontAwesome icons)', max_length=255)),
                ('counter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='api.counter')),
            ],
        ),
    ]
