# Generated by Django 5.1.4 on 2025-01-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_counter_icon_remove_counter_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='icon',
            field=models.CharField(blank=True, help_text='Icon for the statistic (e.g., fa-users for FontAwesome icons)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='counter',
            name='label',
            field=models.CharField(blank=True, help_text='Label for the statistic (e.g., Users, Subscribes)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='counter',
            name='value',
            field=models.CharField(blank=True, help_text='Value of the statistic (e.g., 2.7K, 1.8K)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='counter',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the content section', null=True),
        ),
        migrations.AlterField(
            model_name='counter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='counters/'),
        ),
        migrations.AlterField(
            model_name='counter',
            name='title',
            field=models.CharField(blank=True, help_text='Title of the content section', max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='CounterDetail',
        ),
    ]
