# Generated by Django 5.1.4 on 2025-01-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_counter_icon_counter_label_counter_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counter',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='counter',
            name='label',
        ),
        migrations.RemoveField(
            model_name='counter',
            name='value',
        ),
        migrations.AddField(
            model_name='counter',
            name='icon_1',
            field=models.CharField(default=1, help_text='Icon for the statistic (e.g., fa-users for FontAwesome icons)', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counter',
            name='icon_2',
            field=models.CharField(default=1, help_text='Icon for the statistic (e.g., fa-users for FontAwesome icons)', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counter',
            name='icon_3',
            field=models.CharField(default=1, help_text='Icon for the statistic (e.g., fa-users for FontAwesome icons)', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counter',
            name='icon_4',
            field=models.CharField(default=1, help_text='Icon for the statistic (e.g., fa-users for FontAwesome icons)', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counter',
            name='label_1',
            field=models.CharField(default=1, help_text='Label for the statistic (e.g., Users, Subscribes)', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counter',
            name='label_2',
            field=models.CharField(default=1, help_text='Label for the statistic (e.g., Users, Subscribes)', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counter',
            name='label_3',
            field=models.CharField(default=1, help_text='Label for the statistic (e.g., Users, Subscribes)', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counter',
            name='label_4',
            field=models.CharField(default=1, help_text='Label for the statistic (e.g., Users, Subscribes)', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counter',
            name='value_1',
            field=models.CharField(default=1, help_text='Value of the statistic (e.g., 2.7K, 1.8K)', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counter',
            name='value_2',
            field=models.CharField(default=1, help_text='Value of the statistic (e.g., 2.7K, 1.8K)', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counter',
            name='value_3',
            field=models.CharField(default=1, help_text='Value of the statistic (e.g., 2.7K, 1.8K)', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counter',
            name='value_4',
            field=models.CharField(default=1, help_text='Value of the statistic (e.g., 2.7K, 1.8K)', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='counter',
            name='description',
            field=models.TextField(default=1, help_text='Description of the content section'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='counter',
            name='image',
            field=models.ImageField(default=1, upload_to='counters/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='counter',
            name='title',
            field=models.CharField(default=1, help_text='Title of the content section', max_length=255),
            preserve_default=False,
        ),
    ]
