# Generated by Django 5.1.4 on 2025-01-02 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_counter_icon_remove_counter_label_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counter',
            old_name='icon_1',
            new_name='icon',
        ),
        migrations.RenameField(
            model_name='counter',
            old_name='label_1',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='counter',
            old_name='value_1',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='counter',
            name='icon_2',
        ),
        migrations.RemoveField(
            model_name='counter',
            name='icon_3',
        ),
        migrations.RemoveField(
            model_name='counter',
            name='icon_4',
        ),
        migrations.RemoveField(
            model_name='counter',
            name='label_2',
        ),
        migrations.RemoveField(
            model_name='counter',
            name='label_3',
        ),
        migrations.RemoveField(
            model_name='counter',
            name='label_4',
        ),
        migrations.RemoveField(
            model_name='counter',
            name='value_2',
        ),
        migrations.RemoveField(
            model_name='counter',
            name='value_3',
        ),
        migrations.RemoveField(
            model_name='counter',
            name='value_4',
        ),
    ]
