# Generated by Django 5.1.4 on 2025-01-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rename_icon_1_counter_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowItWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main title displayed on the page', max_length=255)),
                ('description_1', models.TextField(help_text='First paragraph description')),
                ('description_2', models.TextField(blank=True, help_text='Second paragraph description', null=True)),
                ('description_3', models.TextField(blank=True, help_text='Third paragraph description', null=True)),
                ('description_4', models.TextField(blank=True, help_text='Fourth paragraph description', null=True)),
                ('video_url', models.CharField(help_text='Normal YouTube link for the video', max_length=255)),
            ],
        ),
    ]
