# Generated by Django 5.1.4 on 2025-01-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_howitworks'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowItWorksStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='how_it_works_icons/')),
            ],
            options={
                'ordering': ['step_number'],
            },
        ),
        migrations.DeleteModel(
            name='HowItWorks',
        ),
    ]
