# Generated by Django 5.1.4 on 2025-01-14 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_howitworksstep_delete_howitworks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HowItWorksStep',
            new_name='HowitWorks',
        ),
    ]
