# Generated by Django 5.1.4 on 2025-01-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_rename_howitworksstep_howitworks'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumelayout',
            name='image_3',
            field=models.ImageField(blank=True, help_text='Upload the second image for the resume template (optional)', null=True, upload_to='resume_templates/'),
        ),
    ]
