# Generated by Django 5.1.4 on 2025-01-15 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_resumelayout_image_3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumelayout',
            name='image_3',
        ),
    ]
